name: Java CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OSSRH Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with tests
        run: mvn -B clean package
