name: Manual Rollback
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}

      - name: Configure Git user
        run: |
          git config user.email $USER_EMAIL
          git config user.name $USER_NAME
        env:
          USER_EMAIL: silva.gp.miguel@gmail.com
          USER_NAME: silvagpmiguel

      - name: Rollback
        run: mvn release:rollback
